language: node_js
node_js:
- "10"
cache:
  directories:
  - node_modules
env:
  global:
  - PATH=$HOME/.wantedly/bin:$PATH
install:
- npm install
script:
- npm run build
- npm test
before_deploy:
- npm run publish
deploy:
- provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: 'web-ext-artifacts/*'
  on:
    tags: true
