language: node_js
node_js:
- "10"
cache:
  directories:
  - node_modules
env:
  global:
  - PATH=$HOME/.wantedly/bin:$PATH
  # WEB_EXT_API_KEY
  - secure: "LUn7aIbRVSet8L201aoD8dxc96/+B2fhzCICfeNUoAMfdEL8OjVGfZsDyCIzM5gTvmGgKhncDQBHobiWhH8LNkGa/8oTf+ccrH5Hm/WqAS5YUs2nVScwekbXqxzEURJmAXVHznC739gWp8amL3xgjj2QL+0JB4en+YkYyh6T1QTG96oNCeEsZCiDq7xGXOjI3IgIe1FXYJd3jnIQpmMvHJdVtpYofFPjJb+Z3KD8zqA4X95Sj7kY/i5UcuVziaL0Va7RoncVJrBaqB3eWmi1/9PNKCo6vKLB36tgP8xcSymrzIjzFZY8HQ+RJW0+zNEL32ceG4XzNRhZw5HRl3vk5dlCVISjCTZ9Q7NsI20NF/LoK/f7Ldt0XKYPICYDE5/+CDuFIw3ca+xoL7ReRAmyfrg2L6cfLfdFAPFpiJcTECHXalVm3WbHaTXxQwi2Ar1K2jbgt+9dihHVMiaYjsd6t8Dwab48BUjQBptVy/5cJeZ+XDHqNd4yd70bUteIypfXfWZPSJ0wF03wqjlsEQO9Aeo/wl8gVBNvQXy7/aMCMDlBXWec5LIIsUcx2/PYajuZD6wAbzucRZc4vSS2Zq1h5J7e0tZSU/kGJPL4yIb2o1pjpDCRLL/M4yoFgBakcJceFTHxAYQifXP5w4YZkw6oLdVB+R+t14jZlNq0a2nO+Ms="
  # WEB_EXT_API_SECRET
  - secure: "sKrFGETDuAXJZLMLiRiGB9gCJFYnETm1yOw3czsU9nJhbyRrmBuWz62JauMHySxsFLvIW6ABqHAv8yaUPyxI5NjNp/juBJOlKSWlYlqdZW8stMem3hOmWS7aWOjlcFPZplCCkFixajHO++pxaR69iMW6rSXvZCDioU1HaonTgirWTN2IJ3u4jwScolt1niYw0JCFu9/TVt1LqZRdNGU6/4LvQhSndPZddnSff2IEFa2BeThonRFNWvmmzygbcWCo+t0DeRcIkeZF6D2kC6IRCZkV9JGiMkFNUO8XzKKuTRMpDIxhs7VFN6sIgEdNAnSg6wGbC7BHCy9sxYjG5opz40VixfmpwuQzS02y/PDc1JVcPWcw1Vp5HMTm7EWeOvSldihsPGmtVnHHLx0YF11qiRdWiYq/IZla9fioJnM6E8zTbKzAillUT8InpyJseZ1q+8You0mWeDQNomj417XOSI3Mv96bX2X4OeZMYD4gU8wx5Tj9uS7k0Os6oZN1PWW4/BTJfOkAHCRiW+D3ws8jDHpyUKs5/ovJ21ywBmxTq3ZqviUlB3ncx2aRsd/hn7hV6IZdY2oPbPr/QjFJvo5cjv0kSiRYquBEu2EdRf/TVpb5kB/6M4nfHjBAJnBKFJAEENJRDXNDUvBWanHkCEaohg2lKiv7meiD0P63fkTE9ak="
  # GITHUB_TOKEN
  - secure: "BOXicD09osUTHSDZPhnxGtFKwPq/cJtopBhEPEB9hIIxz2DShUtb5KRKjtQc1o33IVdrcpoiA1/fL3ABzEu8/2s5XZuIV4zfAPbYJlwtw0i5SONkCyr57EMVFouiE9DA3GXK6MhTMCxErL232rrHqlnwT5xtkF6GhOwavMWyHksAKA09qN2wWtyF69HBZ7lzjAPtI/xYtuMRqsbVY79jHbYdEAMvgqBFTC/VVPPCZ/Q8Xy3W0h58IKQlJ7QdTZWaqLer5kLwiWwXeolge0miRSZUSDUstZy5r0yjxsHh72lTR6IEwozyAPLHHRsaUxhGXruszSYcUtJzUu4xh21Y0WSFdmatpczZL15KnJRmm4YcMdIKDaPHli72Cqt5GV+GUYdWIz7hDk5dwdON2jNGb5Lj7Yat2DvHPOGlKWGoZCEqNinh0Ox74jEyAXYSx8D9hWvuaMFt5PH7ETqmIuezNma9NPpxPrTySt/C5uIgZ6vEUxEVhWMIi9WqzntC+PHmWDO+GnmH/PYSsxgUkr2QbeAEAgYBw1qHXmd+mz6nyRP7Lwrxa3nuGCMwLEWL9OvI5AHwIBBoIn4I/XWYtHpg9OV2/978HrXJ5zwgueJqrIuHedMD8FuJxN7F4H+GzTbSK77eP8QXk0cbWVhSN1WpAWNyRtegsE7q2570HQDHKj8="
install:
- npm install
script:
- npm run build
- npm test
before_deploy:
- npm run sign
deploy:
- provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: 'web-ext-artifacts/*'
  on:
    tags: true
