name: publish
on:
  release:
    types:
      - released
jobs:
  publish:
    runs-on: ubuntu-20.04
    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      EXTENSION_ID: ${{ secrets.EXTENSION_ID }}
      JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
    strategy:
      matrix:
        browser:
          - firefox
          - chrome
    steps:
      - uses: actions/checkout@v2
      - id: node-version
        run: echo "::set-output name=version=$(cat .node-version)"
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.node-version.output.version }}
          cache: npm
      - run: npm install
      - run: npm run build
      - run: npm run publish:${{ matrix.browser }}
