name: release
on:
  push:
    branches:
      - master
jobs:
  update-draft-release:
    runs-on: ubuntu-20.04
    steps:
      - id: release-drafter
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - id: node-version
        run: echo "::set-output name=version=$(cat .node-version)"
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.node-version.output.version }}
      - run: npm install
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git reset --hard
          git clean -fd
          npm version ${VERSION#v} --no-git-tag-version
        env:
          VERSION: ${{ steps.release-drafter.outputs.tag_name }}
      - id: pr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: ${{ steps.release-drafter.outputs.tag_name }}
          committer: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          branch: bump-version-${{ steps.release-drafter.outputs.tag_name }}
          base: master
          delete-branch: true
          title: ${{ steps.release-drafter.outputs.tag_name }}
          body: ""
      - run: gh pr merge ${{ steps.pr.outputs.pull-request-url }} --auto
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.pr.outputs.pull-request-url != null }}
      - run: npm run build
      - uses: bgpat/release-asset-action@master
        with:
          pattern: web-ext-artifacts/*
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-id: ${{ steps.release-drafter.outputs.id }}
          allow-overwrite: true
