name: release
on:
  push:
    branches:
      - master
jobs:
  update-draft-release:
    runs-on: ubuntu-20.04
    steps:
      - id: release-drafter
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - id: node-version
        run: echo "::set-output name=version=$(cat .node-version)"
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.node-version.output.version }}
      - run: npm install
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git reset --hard
          git clean -fd
          if npm version ${VERSION#v} --no-git-tag-version; then
            git commit -am $VERSION
            git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:refs/heads/master
          fi
        env:
          VERSION: ${{ steps.release-drafter.outputs.tag_name }}
      - run: npm run build
      - uses: bgpat/release-asset-action@master
        with:
          pattern: web-ext-artifacts/*
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-id: ${{ steps.release-drafter.outputs.id }}
          allow-overwrite: true
